networks:
  basic-client:
    name: basic-client-network

services:

  ldio-workbench:
    image: openldes/ldi-orchestrator:latest
    network_mode: "host"
    ports:
      - 9006:8080
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]


  sink-system:
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:8080
    networks:
      - basic-client
    environment:
      - MEMORY=true
      - MEMBER_TYPE=http://schema.mobivoc.org/#ParkingLot
