networks:
  basic-setup:
    name: basic-setup_ldes-network

services:

  ldes-postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5432:5432
    networks:
      - basic-setup


  ldes-server:
    image: openldes/ldes-server:latest
    environment:
      - SIS_DATA=/tmp
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - LDESSERVER_HOSTNAME=http://localhost:9003/ldes
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
      - MANAGEMENT_TRACING_ENABLED=false
      - SPRING_TASK_SCHEDULING_POOL_SIZE=5
      - LDESSERVER_FRAGMENTATIONCRON=*/1 * * * * *
      - LDESSERVER_MAINTENANCECRON=-  # no retention / compaction / deletion
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:8080
    networks:
      - basic-setup
    depends_on:
      - ldes-postgresdb
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://ldes-server:8080/ldes/actuator/health"]


  ldio-workbench:
    image: openldes/ldi-orchestrator:latest
    volumes:
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9004:8080
    networks:
      - basic-setup
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://ldio-workbench:8080/actuator/health"]
