networks:
  enrich-model:
    name: enrich-model-network

services:

  graph-database:
    image: eclipse/rdf4j-workbench:latest
    ports:
      - 9008:8080
    networks:
      - enrich-model
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "-H", "'application/sparql-results+xml'", "http://graph-database:8080/rdf4j-server/repositories"]


  ldio-workbench:
    image: openldes/ldi-orchestrator:latest
    environment:
      - LOGGING_LEVEL_ROOT=INFO
    ports:
      - 9006:8080
    networks:
      - enrich-model
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://ldio-workbench:8080/actuator/health"]


  sink-system:
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:8080
    networks:
      - enrich-model
    environment:
      - MEMORY=true
      - MEMBER_TYPE=http://schema.org/Person
