networks:
  minimal-workbench:
    name: minimal-workbench_ldes-network

services:
  ldio-workbench:
    image: openldes/ldi-orchestrator:latest
    ports:
      - 9004:8080
    networks:
      - minimal-workbench
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://ldio-workbench:8080/actuator/health"]
