networks:
  public-ldes:
    name: public-ldes-network

services:

  ### -- Data Client --

  ldio-workbench:
    image: openldes/ldi-orchestrator:latest
    environment:
    ports:
      - 9006:8080
    networks:
      - public-ldes 
    depends_on:
      - sink-system
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://ldio-workbench:8080/actuator/health"]


  ### -- Backend System --

  sink-system:
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:8080
    networks:
      - public-ldes
    depends_on:
      - sink-database
    environment:
      - MEMBER_TYPE=https://implementatie.data.vlaanderen.be/ns/verkeersmetingen#Verkeerstelling
      - CONNECTION_URI=mongodb://sink-database
      - DATABASE_NAME=public-ldes
      - COLLECTION_NAME=traffic-counts

  sink-database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - public-ldes
